name: SweetHeads
version: 1.0
main: com.tweska.sweetheads.SweetHeadsPlugin
api-version: 1.13
commands:
    updateheads:
      description: Download new heads from online sources.
      usage: /downloadheads